name: Registry.NET CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**" # This is the path to the workflow files
      - "src/**" # Any source files

jobs:
  ci:
    runs-on: windows-latest

    steps:
    - name: 👨‍💻 Checkout code
      uses: actions/checkout@v2

    - name: 🛠️ Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: 👷‍♂️ Build solution
      run: msbuild.exe Substrant.Registry.sln -p:Configuration=Release

    - name: 🚀 Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: bundle
        path: "bin/Release/"